AllCops:
  TargetRubyVersion: 3.0.0

Layout/LineLength:
  Max: 80

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
